# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.96705972839
    has_acceleration_limits: true
    max_acceleration: 7.33038285838 # 原值: 420 deg/s^2
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.00712863979
    has_acceleration_limits: true
    max_acceleration: 10.471975512 # 原值: 600 deg/s^2
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.22885911619
    has_acceleration_limits: true
    max_acceleration: 10.7337748998 # 原值: 615 deg/s^2
  joint_4:
    has_velocity_limits: true
    max_velocity: 4.88692190558
    has_acceleration_limits: true
    max_acceleration: 24.6615023307 # 原值: 1413 deg/s^2
  joint_5:
    has_velocity_limits: true
    max_velocity: 4.27605666739
    has_acceleration_limits: true
    max_acceleration: 42.3242343609 # 原值: 2425 deg/s^2
  joint_6:
    has_velocity_limits: true
    max_velocity: 6.19591884458
    has_acceleration_limits: true
    max_acceleration: 62.8318530718 # 原值: 3600 deg/s^2
