# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 4.53785605519
    has_acceleration_limits: true
    max_acceleration: 13.08996939 # 原值: 750 deg/s^2
  joint_2:
    has_velocity_limits: true
    max_velocity: 3.40339204139
    has_acceleration_limits: true
    max_acceleration: 13.526301703 # 原值: 775 deg/s^2
  joint_3:
    has_velocity_limits: true
    max_velocity: 6.10865238198
    has_acceleration_limits: true
    max_acceleration: 13.962634016 # 原值: 800 deg/s^2
  joint_4:
    has_velocity_limits: true
    max_velocity: 8.37758040957
    has_acceleration_limits: true
    max_acceleration: 54.9778714378 # 原值: 3150 deg/s^2
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: true
    max_acceleration: 33.6848545635 # 原值: 1930 deg/s^2
  joint_6:
    has_velocity_limits: true
    max_velocity: 11.2573736754
    has_acceleration_limits: true
    max_acceleration: 66.3225115758 # 原值: 3800 deg/s^2
